# -*- coding: utf-8 -*-
"""image_comparison

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13J2npGWlfMIHhhtIb-emuDB5EI_HlFg4
"""

from skimage.measure import compare_ssim as ssim
import numpy as np
import cv2
from IPython.display import Image

pip install resize

from resize import resize_image

img = cv2.imread("img.jpg")
img2= cv2.imread("img2.jpg")

img,img2 = resize_image(img,img2)
a = before.shape
b = after.shape

grayA = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
grayB = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)



(score, diff) = ssim(grayA, grayB, full=True)
diff = (diff * 255).astype("uint8")
print("SSIM: {}".format(score))

